import random

link = ["https://techforhack.com/84-woocommerce-extensions-updates/",
       "https://techforhack.com/56-woocommerce-extensions-updates/",
       "https://techforhack.com/newspaper-v10-3-7-wordpress-news-theme/",
       "https://techforhack.com/elementor_pro_3-0-4_nulled/",
       "https://techforhack.com/adobe-cc-2020-universal-crack-for-adobe-cc-2020-full-version/",
       "https://techforhack.com/wireshark-termux/",
       "https://techforhack.com/windows-10-kali-linux-subsystem-full-tutorial/",
       "https://techforhack.com/tool-x/",
       "https://techforhack.com/routersploit/",
       "https://techforhack.com/newspaper-v10-3-7-wordpress-news-theme/",
       "https://techforhack.com/networkingfundamentals/",
       "https://techforhack.com/networkdevices/",
       "https://techforhack.com/portable_hacking_device/",
       "https://techforhack.com/tbomber/",
       "https://techforhack.com/metasploit-termux/",
       "https://techforhack.com/lazy_script/",
       "https://techforhack.com/nethunter-on-android/",
       "https://techforhack.com/install-hidden-eye-advanced-phishing-tool-full-guide/",
       "https://techforhack.com/instagram-tools-hack-insta-from-termux/",
       "https://techforhack.com/black_hydra/",
       "https://techforhack.com/nmap/",
       "https://techforhack.com/hackpro/",
       "https://techforhack.com/fix-any-android-game-lag-in-few-minutes/",
       "https://techforhack.com/elementor_pro_3-0-4_nulled/",
       "https://techforhack.com/ddos-termux/",
       "https://techforhack.com/databasetechnology/",
       "https://techforhack.com/database-models-all-you-need-to-know/",
       "https://techforhack.com/metasploit-payload-termux/"]

url_link = random.choice(link)